<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-StoreExample-DB02BFB1-7C36-4517-9903-AC54E229EA24</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
        <PackageReference Include="Riok.Mapperly" Version="4.2.0-next.2" />
    </ItemGroup>
</Project>
